# Table of Contents
- [Description](#description)
- [Building SOC 2018 to O*NET 2019 Mapping](#building-soc-2018-to-onet-2019-mapping)
    - [Observations: SOC 2018 to O*NET-2019](#observations-soc-2018-to-onet-2019)
- [Building SOC 2010 to SOC 2018 Mapping](#building-soc-2010-to-soc-2018-mapping)
    - [Observations: Building SOC 2010 to SOC 2018 Mapping](#observations-building-soc-2010-to-soc-2018-mapping)
    - [Note](#note)
- [Building SOC 2010 to O*NET 2019 Crosswalk](#building-soc-2010-to-onet-2019-crosswalk)
- [Building 2010 Census Code to 2010 SOC Mapping](#building-2010-census-code-to-2010-soc-mapping)
    - [Observations: Building 2010 Census Code to 2010 SOC Mapping](#observations-building-2010-census-code-to-2010-soc-mapping)
- [Building 2010 Census Code to O*NET-SOC 2019 Crosswalk](#building-2010-census-code-to-onet-soc-2019-crosswalk)
- [ISCO 2008 to SOC 2010 Mapping](#isco-2008-to-soc-2010-mapping)
- [Building ISCO 2008 to O*NET-SOC 2019 Crosswalk](#building-isco-2008-to-onet-soc-2019-crosswalk)

# Description
The purpose of this notebook is to build the CSV that provides a mapping from each GSS Occupation Code (based on the SOC 2010 Census codes) to an O*NET-SOC 2019 Occupation Code.

Using the following crosswalks in `/data/crosswalks/`:
- `census_soc_2010_crosswalk.csv`
- `census2010_to_onet2019.csv`
- `onet2019_to_soc2018_crosswalk.csv`
- `soc2010_to_soc2018_crosswalk.csv`

This notebook constructs a crosswalk between GSS occupation codes (which are equivalent to the 2010 Census occupation codes) and O*NET-SOC 2019 occupation codes.

The resulting CSV file is stored under `/data/crosswalks/census2010_to_onet2019.csv`

In the case where one code maps to multiple other codes, tiebreaks will be determined using the following methods:
1. Exact job title matching
2. Bureau of Labor Statistics (BLS) historical data on total employment, to maximize coverage
3. Manual matching

# Building SOC 2018 to O*NET-2019 mapping

In [1]:
import pandas as pd
import csv

data_dir = "../../data/"
crosswalk_dir = data_dir + "crosswalks/"

# Read data into DataFrames
df_gss_soc = pd.read_csv(crosswalk_dir + "census_soc_2010_crosswalk.csv")
df_onet2019_soc2018 = pd.read_csv(crosswalk_dir + "onet2019_to_soc2018_crosswalk.csv")
df_soc2010_soc2018 = pd.read_csv(crosswalk_dir + "soc2010_to_soc2018_crosswalk.csv")

In [2]:
df_onet2019_soc2018.head()

,O*NET-SOC 2019 Code,O*NET-SOC 2019 Title,2018 SOC Code,2018 SOC Title
0,11-1011.00,Chief Executives,11-1011,Chief Executives
1,11-1011.03,Chief Sustainability Officers,11-1011,Chief Executives
2,11-1021.00,General and Operations Managers,11-1021,General and Operations Managers
3,11-1031.00,Legislators,11-1031,Legislators
4,11-2011.00,Advertising and Promotions Managers,11-2011,Advertising and Promotions Managers

In [3]:
df_onet2019_soc2018["O*NET-SOC 2019 Code"].duplicated().sum()

np.int64(0)

In [4]:
ambiguous_mask = df_onet2019_soc2018["2018 SOC Code"].duplicated(keep=False)
ambiguous_mask.sum()

np.int64(225)

### Observations: SOC 2018 to O*NET-2019
There are 149 ambiguous mappings (where one SOC 2018 code maps to many O*NET-SOC 2019 codes).

This will be handled by checking that for every ambiguous mapping, there is a "general" O*NET-SOC 2019 code (i.e. a code that ends with `.00`) that corresponds to each respective ambiguous SOC 2018 code.

In [5]:
# Filter into two DataFrames: 
# 1. Ambiguous, which indicates O*NET-SOC 2019 maps to multiple 2018 SOC
# 2. Unambiguous, which indicates each O*NET-SOC 2019 maps to one 2018 SOC
df_onet_soc2018_unambiguous = df_onet2019_soc2018[~ambiguous_mask]
df_onet_soc2018_ambiguous = df_onet2019_soc2018[ambiguous_mask]

df_onet_soc2018_ambiguous

,O*NET-SOC 2019 Code,O*NET-SOC 2019 Title,2018 SOC Code,2018 SOC Title
0,11-1011.00,Chief Executives,11-1011,Chief Executives
1,11-1011.03,Chief Sustainability Officers,11-1011,Chief Executives
10,11-3013.00,Facilities Managers,11-3013,Facilities Managers
11,11-3013.01,Security Managers,11-3013,Facilities Managers
13,11-3031.00,Financial Managers,11-3031,Financial Managers
...,...,...,...,...
975,53-6051.00,Transportation Inspectors,53-6051,Transportation Inspectors
976,53-6051.01,Aviation Inspectors,53-6051,Transportation Inspectors
977,53-6051.07,"Transportation Vehicle, Equipment and Systems ...",53-6051,Transportation Inspectors
986,53-7062.00,"Laborers and Freight, Stock, and Material Move...",53-7062,"Laborers and Freight, Stock, and Material Move..."
987,53-7062.04,Recycling and Reclamation Workers,53-7062,"Laborers and Freight, Stock, and Material Move..."

In [6]:
# Check every ambiguous SOC 2018 code mapping has general .00 code
df_onet_occ = pd.read_csv(data_dir + "onet_misc/occupation_data.csv")
onet2019_codes = set(df_onet_occ["O*NET-SOC Code"])

onet2019_to_soc2018 = {onet:soc for onet,soc 
                       in zip(df_onet_soc2018_unambiguous["O*NET-SOC 2019 Code"], 
                              df_onet_soc2018_unambiguous["2018 SOC Code"])}

# For every general code, add to our dictionary as 
    # [general_code:soc_code]
for idx,row in df_onet_soc2018_ambiguous.iterrows():
    soc_code = row["2018 SOC Code"]
    general_code = soc_code + ".00"
    if general_code in onet2019_to_soc2018:
        continue
    elif general_code in onet2019_codes:
        # This theoretically shouldn't happen
        onet2019_to_soc2018[general_code] = soc_code

if len(onet2019_to_soc2018) != df_onet2019_soc2018["2018 SOC Code"].nunique():
    print("[WARNING] We have not covered all valid SOC 2018 Codes")
else:
    print("[INFO] All SOC 2018 Codes have a corresponding O*NET 2019 Code")

# Flip our dictionary. This will be dict use for GSS to O*NET-2019 mapping
soc2018_to_onet2019 = {soc:onet for onet,soc in onet2019_to_soc2018.items()}

[INFO] All SOC 2018 Codes have a corresponding O*NET 2019 Code

# Building SOC 2010 to SOC 2018 Mapping

In [7]:
df_soc2010_soc2018.head()

,2010 SOC Code,2010 SOC Title,2018 SOC Code,2018 SOC Title
0,11-1011,Chief Executives,11-1011,Chief Executives
1,11-1021,General and Operations Managers,11-1021,General and Operations Managers
2,11-1031,Legislators,11-1031,Legislators
3,11-2011,Advertising and Promotions Managers,11-2011,Advertising and Promotions Managers
4,11-2021,Marketing Managers,11-2021,Marketing Managers

In [8]:
ambiguous_mask = df_soc2010_soc2018["2010 SOC Code"].duplicated(keep=False)
ambiguous_mask.sum()

np.int64(102)

### Observations: Building SOC 2010 to SOC 2018 Mapping
`df_soc2010_soc2018["2010 SOC Code"].duplicated().sum()` yields 60, meaning there are 60 codes from the SOC 2010 batch that map onto multiple 2018 SOC Codes. 

This will be handled by constructing two dictionaries: an `unambiguous` dictionary, containing mappings from SOC 2010 codes to SOC 2018 codes that are unambiguous (one to one), and an `ambiguous` dictionary, containing mappings from SOC 2010 codes to multiple SOC 2018 codes (one to many).

The "true" mappings for the `ambiguous` dictionary will be determined through a `tiebreaker()` method, where we pull from BLS data to determine which job code employed more people in the year of 2018 (for better coverage).

In [9]:
# Load BLS data for 2021
df_bls = pd.read_excel(crosswalk_dir + "bls_2021.xlsx")
print(f"[INFO] Columns are: {df_bls.columns}")

df_bls.head()

[INFO] Columns are: Index(['AREA', 'AREA_TITLE', 'AREA_TYPE', 'PRIM_STATE', 'NAICS', 'NAICS_TITLE',
       'I_GROUP', 'OWN_CODE', 'OCC_CODE', 'OCC_TITLE', 'O_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT',
       'H_MEAN', 'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN',
       'H_PCT75', 'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75',
       'A_PCT90', 'ANNUAL', 'HOURLY'],
      dtype='str')

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,22,32.98,49.43,23980,29950,45760,68590,102810,NaN,NaN
1,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,49.25,77.39,#,47860,74710,102450,160960,#,NaN,NaN
2,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1000,Top Executives,...,47.46,77.18,#,41260,60900,98720,160540,#,NaN,NaN
3,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1010,Chief Executives,...,86.31,#,#,60300,111080,179520,#,#,NaN,NaN
4,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,86.31,#,#,60300,111080,179520,#,#,NaN,NaN

In [10]:
# Filter df_bls to the columns of interest since full DataFrame is large
# Convert TOT_EMP to integer
cols = ["OCC_CODE", "TOT_EMP"]
df_bls = df_bls[cols]
df_bls["TOT_EMP"] = pd.to_numeric(df_bls["TOT_EMP"], errors="coerce").astype("Int64")

In [11]:
# Get our ambiguous and unambiguous DataFrames
# Similar to before:
    # 1. Ambiguous is one SOC 2010 code to many SOC 2018 codes
    # 2. Unambiguous is one SOC 2010 code to one SOC 2018 codes
df_soc2010_soc2018_ambiguous = df_soc2010_soc2018[ambiguous_mask]
df_soc2010_soc2018_unambiguous = df_soc2010_soc2018[~ambiguous_mask]

In [12]:
# Build temp overall dictionary:
temp_soc2010_to_soc2018 = {}
for idx, row in df_soc2010_soc2018.iterrows():
    soc2010 = row["2010 SOC Code"]
    soc2019 = row["2018 SOC Code"]
    temp_soc2010_to_soc2018.setdefault(soc2010, []).append(soc2019)

In [13]:
# Build our disjoint unambiguous and ambiguous dictionaries
soc2010_to_soc2018 = {}
ambiguous_soc2010_to_soc2018 = {}
for soc2010, candidates in temp_soc2010_to_soc2018.items():
    if len(candidates) == 1:
        soc2010_to_soc2018[soc2010] = candidates[0]
    else:
        ambiguous_soc2010_to_soc2018[soc2010] = candidates

In [14]:
def tiebreaker(candidates, df_bls, occ_code="OCC_CODE", tot_emp="TOT_EMP"):
    '''Description: Tiebreaker, returns candidate with greatest total employed'''
    totals = (
        df_bls[df_bls[occ_code].isin(candidates)]
        .groupby(occ_code)[tot_emp]
        .sum()
        .reindex(candidates, fill_value=0)  # preserve candidates' order, 0 for missing ones
    )

    if totals.max() <= 0:
        return None

    return totals.idxmax()

# For SOC 2010 codes that are one to many, use tiebreaker() for best candidate
for soc2010, candidates in ambiguous_soc2010_to_soc2018.items():
    soc2018 = tiebreaker(candidates, df_bls)
    soc2010_to_soc2018[soc2010] = soc2018

In [15]:
# Check that we have good coverage after
full_coverage = (len(soc2010_to_soc2018) 
                 == df_soc2010_soc2018["2010 SOC Code"].nunique())

if not full_coverage:
    print("[WARNING] We have not covered all SOC 2010 Codes")
else:
    print("[INFO] All SOC 2010 Codes have an entry")

[INFO] All SOC 2010 Codes have an entry

In [16]:
# Now check if there are any 2010 SOC codes with entry but no BLS coverage
    # This might be because BLS did not collect data on that certain occupation
# SOC 2010 to SOC 2018 candidate map:
no_bls_coverage = {}
for key,val in soc2010_to_soc2018.items():
    if val is None:
        candidates = ambiguous_soc2010_to_soc2018[key]
        no_bls_coverage[key] = candidates
        
        print(f"[WARNING] Must be resolved manually for SOC 2010 Code: {key}")
        print(f"[INFO] Corresponding candidates: {candidates}\n")

[WARNING] Must be resolved manually for SOC 2010 Code: 13-2021
[INFO] Corresponding candidates: ['13-2022', '13-2023']

[WARNING] Must be resolved manually for SOC 2010 Code: 25-2052
[INFO] Corresponding candidates: ['25-2055', '25-2056']

[WARNING] Must be resolved manually for SOC 2010 Code: 25-9041
[INFO] Corresponding candidates: ['25-9042', '25-9043', '25-9049']

[WARNING] Must be resolved manually for SOC 2010 Code: 53-1031
[INFO] Corresponding candidates: ['53-1043', '53-1044', '53-1049']

In [17]:
# Check if any job titles in candidates exactly match the parent
resolved = []
for soc2010,candidates in no_bls_coverage.items():
    mask = df_soc2010_soc2018["2010 SOC Code"] == soc2010
    soc2010_jobtitle = (df_soc2010_soc2018[mask]["2010 SOC Title"]
                        .unique()[0]
                        .replace("(#)", "")
                        .strip())

    for c in candidates:
        mask = df_soc2010_soc2018["2018 SOC Code"] == c
        c_jobtitle = (df_soc2010_soc2018[mask]["2018 SOC Title"]
                      .unique()[0]
                      .replace("(#)", "")
                      .strip())
        if c_jobtitle == soc2010_jobtitle:
            soc2010_to_soc2018[soc2010] = c
            print(f"[INFO] Was able to resolve 2010 Code {soc2010} with",
                  "2018 code {c} through job title matching")
            resolved.append(soc2010)
            break

# Remove resolved items from dictionary
for code in resolved:
    del no_bls_coverage[code]

# Print info on items that must be manually resolved
for code, candidates in no_bls_coverage.items():
    print(f"[WARNING] Must be resolved manually for SOC 2010 Code: {code}")
    print(f"[INFO] Corresponding candidates: {candidates}\n")

[INFO] Was able to resolve 2010 Code 13-2021 with 2018 code {c} through job title matching
[WARNING] Must be resolved manually for SOC 2010 Code: 25-2052
[INFO] Corresponding candidates: ['25-2055', '25-2056']

[WARNING] Must be resolved manually for SOC 2010 Code: 25-9041
[INFO] Corresponding candidates: ['25-9042', '25-9043', '25-9049']

[WARNING] Must be resolved manually for SOC 2010 Code: 53-1031
[INFO] Corresponding candidates: ['53-1043', '53-1044', '53-1049']

In [18]:
# Manually hardcode/override for the keys whose candidates don't have BLS coverage
soc2010_to_soc2018["25-2052"] = "25-2056"
soc2010_to_soc2018["25-9041"] = "25-9042"
soc2010_to_soc2018["53-1031"] = "53-1043"

### Note
In the cells below, we add SOC 2010 codes in Census 2010 to SOC 2010 crosswalk that are not in SOC 2010 to SOC 2018. 

This is because according to BLS, the SOC 2010 to SOC 2018 crosswalk only publishes codes which have changed between iterations (i.e. if SOC 2010 is not in the crosswalk, that means that SOC 2018 is exactly the same).

Therefore, for each SOC 2010 code missing in the crosswalk, we find the closest/best SOC 2010 codes in the SOC 2010 to SOC 2018 crosswalk.
- Another thing: I did consider whether, since the SOC 2010 to SOC 2018 codes did not change throughout iterations, if there was a direct mapping between any of the SOC 2010 code and the O*NET-SOC 2019 code, but there was not.

In [19]:
def get_soc2010_prefix_length(soc2010):
    '''Prefix of SOC 2010 code is part that is not continuous zeroes'''
    digits = soc2010.replace("-", "")
    last_nonzero_idx = max(i for i,d in enumerate(digits) if d != "0")
    return last_nonzero_idx + 1

def get_children(soc2010_code, df_soc2010_soc2018):
    '''Determines which SOC 2010 codes in df_soc2010_soc2018 
       are similar to the target soc2010_code'''
    prefix_length = get_soc2010_prefix_length(soc2010_code)
    prefix = soc2010_code.replace("-", "")[:prefix_length]
    children = set()

    for soc2018 in df_soc2010_soc2018["2010 SOC Code"].unique():
        cand_prefix = soc2018.replace("-", "")[:prefix_length]
        if cand_prefix == prefix:
            children.add(soc2018)

    return children

unresolved = {}
for codes in df_gss_soc["2010 SOC Code"].unique():
    # split just in case since census to SOC 2010 expand horiz
    codes = [item.strip() for item in codes.split(",")]
    for soc2010 in codes:
        if soc2010 not in soc2010_to_soc2018:
            candidates = get_children(soc2010, df_soc2010_soc2018)
            if len(candidates) == 1:
                related_soc2010 = candidates.pop()
                soc2010_to_soc2018[soc2010] = soc2010_to_soc2018[related_soc2010]
                print(f"[INFO] Resolved {soc2010}")
            else:
                unresolved[soc2010] = candidates

In [20]:
# Try and match by exact job title match
resolved = set()
for soc2010, candidates in unresolved.items():
    soc2010_mask = df_gss_soc["2010 SOC Code"] == soc2010
    title = df_gss_soc[soc2010_mask]["Occupation Title"].unique()[0]

    for c in candidates:
        c_mask = df_soc2010_soc2018["2010 SOC Code"] == c
        c_title = (df_soc2010_soc2018[c_mask]["2010 SOC Title"]
                   .unique()[0].replace("(#)", "")
                   .strip())
        if c_title == title:
            soc2010_to_soc2018[soc2010] = soc2010_to_soc2018[c]
            resolved.add(soc2010)
            print(f"[INFO] Resolved code {soc2010} with code {c} through job title matching")
            break

while resolved:
    soc2010 = resolved.pop()
    del unresolved[soc2010]

[INFO] Resolved code 41-2010 with code 41-2011 through job title matching

In [21]:
# Load BLS data for 2016
df_bls = pd.read_excel(crosswalk_dir + "bls_2016.xlsx")
print(f"[INFO] Columns are: {df_bls.columns}")
df_bls.head()

[INFO] Columns are: Index(['area', 'area_title', 'area_type', 'naics', 'naics_title', 'own_code',
       'occ code', 'occ title', 'group', 'tot_emp', 'emp_prse', 'jobs_1000',
       'loc_quotient', 'pct_total', 'h_mean', 'a_mean', 'mean_prse', 'h_pct10',
       'h_pct25', 'h_median', 'h_pct75', 'h_pct90', 'a_pct10', 'a_pct25',
       'a_median', 'a_pct75', 'a_pct90', 'annual', 'hourly'],
      dtype='str')

,area,area_title,area_type,naics,naics_title,own_code,occ code,occ title,group,tot_emp,...,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90,annual,hourly
0,99,U.S.,1,000000,Cross-industry,1235.0,00-0000,All Occupations,total,140400040,...,17.81,28.92,45.45,19290,24140,37040,60150,94540,NaN,NaN
1,99,U.S.,1,000000,Cross-industry,1235.0,11-0000,Management Occupations,major,7090790,...,48.46,70.72,#,47330,68630,100790,147090,#,NaN,NaN
2,99,U.S.,1,000000,Cross-industry,1235.0,11-1000,Top Executives,minor,2465800,...,49.19,78.35,#,42810,65420,102320,162970,#,NaN,NaN
3,99,U.S.,1,000000,Cross-industry,1235.0,11-1010,Chief Executives,broad,223260,...,87.12,#,#,69780,114100,181210,#,#,NaN,NaN
4,99,U.S.,1,000000,Cross-industry,1235.0,11-1011,Chief Executives,detailed,223260,...,87.12,#,#,69780,114100,181210,#,#,NaN,NaN

In [22]:
# Filter out to only the columns of interest since df_bls is large
cols = ["occ title", "occ code", "tot_emp"]
df_bls = df_bls[cols]
df_bls["tot_emp"] = pd.to_numeric(df_bls["tot_emp"], errors="coerce").astype("Int64")

In [23]:
# Try to resolve using BLS data, choosing candidate with most total employed
for soc2010, candidates in unresolved.items():
    related_soc2010 = tiebreaker(candidates, df_bls, 
                                 occ_code = "occ code", 
                                 tot_emp="tot_emp")
    if related_soc2010 is None:
        continue
    
    soc2010_to_soc2018[soc2010] = soc2010_to_soc2018[related_soc2010]
    resolved.add(soc2010)
    print(f"[INFO] Resolved code {soc2010}",
          f"with code {related_soc2010} through BLS total employment data.")

while resolved:
    soc2010 = resolved.pop()
    del unresolved[soc2010]

[INFO] Resolved code 11-2020 with code 11-2022 through BLS total employment data.
[INFO] Resolved code 11-9030 with code 11-9032 through BLS total employment data.
[INFO] Resolved code 13-1030 with code 13-1031 through BLS total employment data.
[INFO] Resolved code 13-1070 with code 13-1071 through BLS total employment data.
[INFO] Resolved code 13-2070 with code 13-2072 through BLS total employment data.
[INFO] Resolved code 15-1150 with code 15-1151 through BLS total employment data.
[INFO] Resolved code 15-2090 with code 15-2099 through BLS total employment data.
[INFO] Resolved code 17-1010 with code 17-1011 through BLS total employment data.
[INFO] Resolved code 17-1020 with code 17-1022 through BLS total employment data.
[INFO] Resolved code 17-2070 with code 17-2071 through BLS total employment data.
[INFO] Resolved code 17-2110 with code 17-2112 through BLS total employment data.
[INFO] Resolved code 17-3010 with code 17-3011 through BLS total employment data.
[INFO] Resolved code 17-3020 with code 17-3023 through BLS total employment data.
[INFO] Resolved code 19-1010 with code 19-1013 through BLS total employment data.
[INFO] Resolved code 19-1020 with code 19-1029 through BLS total employment data.
[INFO] Resolved code 19-1030 with code 19-1031 through BLS total employment data.
[INFO] Resolved code 19-1040 with code 19-1042 through BLS total employment data.
[INFO] Resolved code 19-2010 with code 19-2012 through BLS total employment data.
[INFO] Resolved code 19-2030 with code 19-2031 through BLS total employment data.
[INFO] Resolved code 19-2040 with code 19-2041 through BLS total employment data.
[INFO] Resolved code 19-3030 with code 19-3031 through BLS total employment data.
[INFO] Resolved code 19-3090 with code 19-3099 through BLS total employment data.
[INFO] Resolved code 19-4090 with code 19-4099 through BLS total employment data.
[INFO] Resolved code 21-1010 with code 21-1012 through BLS total employment data.
[INFO] Resolved code 21-1020 with code 21-1021 through BLS total employment data.
[INFO] Resolved code 23-1020 with code 23-1023 through BLS total employment data.
[INFO] Resolved code 23-2090 with code 23-2093 through BLS total employment data.
[INFO] Resolved code 25-1000 with code 25-1071 through BLS total employment data.
[INFO] Resolved code 25-2010 with code 25-2011 through BLS total employment data.
[INFO] Resolved code 25-2020 with code 25-2021 through BLS total employment data.
[INFO] Resolved code 25-2030 with code 25-2031 through BLS total employment data.
[INFO] Resolved code 25-2050 with code 25-2052 through BLS total employment data.
[INFO] Resolved code 25-3000 with code 25-3021 through BLS total employment data.
[INFO] Resolved code 25-4010 with code 25-4012 through BLS total employment data.
[INFO] Resolved code 27-1010 with code 27-1011 through BLS total employment data.
[INFO] Resolved code 27-1020 with code 27-1024 through BLS total employment data.
[INFO] Resolved code 27-2020 with code 27-2022 through BLS total employment data.
[INFO] Resolved code 27-2030 with code 27-2031 through BLS total employment data.
[INFO] Resolved code 27-2040 with code 27-2042 through BLS total employment data.
[INFO] Resolved code 27-3010 with code 27-3011 through BLS total employment data.
[INFO] Resolved code 27-3020 with code 27-3022 through BLS total employment data.
[INFO] Resolved code 27-3090 with code 27-3091 through BLS total employment data.
[INFO] Resolved code 27-4010 with code 27-4011 through BLS total employment data.
[INFO] Resolved code 27-4030 with code 27-4032 through BLS total employment data.
[INFO] Resolved code 29-1020 with code 29-1021 through BLS total employment data.
[INFO] Resolved code 29-1060 with code 29-1069 through BLS total employment data.
[INFO] Resolved code 29-2010 with code 29-2011 through BLS total employment data.
[INFO] Resolved code 29-2030 with code 29-2034 through BLS total employment data.
[INFO] Resolved code 29-2050 with code 29-2052 through BLS total employment data.
[INFO] Resolved code 29-2090 with code 29-2099 through BLS total employment data.
[INFO] Resolved code 29-9000 with code 29-9011 through BLS total employment data.
[INFO] Resolved code 31-1010 with code 31-1014 through BLS total employment data.
[INFO] Resolved code 31-2010 with code 31-2011 through BLS total employment data.
[INFO] Resolved code 31-2020 with code 31-2021 through BLS total employment data.
[INFO] Resolved code 33-2020 with code 33-2021 through BLS total employment data.
[INFO] Resolved code 33-3010 with code 33-3012 through BLS total employment data.
[INFO] Resolved code 33-9030 with code 33-9032 through BLS total employment data.
[INFO] Resolved code 35-2010 with code 35-2014 through BLS total employment data.
[INFO] Resolved code 37-3010 with code 37-3011 through BLS total employment data.
[INFO] Resolved code 39-1010 with code 39-1011 through BLS total employment data.
[INFO] Resolved code 39-3010 with code 39-3011 through BLS total employment data.
[INFO] Resolved code 39-3090 with code 39-3091 through BLS total employment data.
[INFO] Resolved code 39-5090 with code 39-5092 through BLS total employment data.
[INFO] Resolved code 39-6010 with code 39-6011 through BLS total employment data.
[INFO] Resolved code 39-7010 with code 39-7011 through BLS total employment data.
[INFO] Resolved code 39-9030 with code 39-9032 through BLS total employment data.
[INFO] Resolved code 41-4010 with code 41-4012 through BLS total employment data.
[INFO] Resolved code 41-9010 with code 41-9011 through BLS total employment data.
[INFO] Resolved code 41-9020 with code 41-9022 through BLS total employment data.
[INFO] Resolved code 43-5030 with code 43-5032 through BLS total employment data.
[INFO] Resolved code 43-6010 with code 43-6014 through BLS total employment data.
[INFO] Resolved code 45-2090 with code 45-2092 through BLS total employment data.
[INFO] Resolved code 45-4020 with code 45-4022 through BLS total employment data.
[INFO] Resolved code 47-2020 with code 47-2021 through BLS total employment data.
[INFO] Resolved code 47-2040 with code 47-2044 through BLS total employment data.
[INFO] Resolved code 47-2050 with code 47-2051 through BLS total employment data.
[INFO] Resolved code 47-2080 with code 47-2081 through BLS total employment data.
[INFO] Resolved code 47-2130 with code 47-2131 through BLS total employment data.
[INFO] Resolved code 47-2150 with code 47-2152 through BLS total employment data.
[INFO] Resolved code 47-3010 with code 47-3013 through BLS total employment data.
[INFO] Resolved code 47-4090 with code 47-4099 through BLS total employment data.
[INFO] Resolved code 47-5010 with code 47-5013 through BLS total employment data.
[INFO] Resolved code 47-5040 with code 47-5041 through BLS total employment data.
[INFO] Resolved code 49-2020 with code 49-2022 through BLS total employment data.
[INFO] Resolved code 49-3040 with code 49-3042 through BLS total employment data.
[INFO] Resolved code 49-3050 with code 49-3053 through BLS total employment data.
[INFO] Resolved code 49-3090 with code 49-3093 through BLS total employment data.
[INFO] Resolved code 49-9010 with code 49-9012 through BLS total employment data.
[INFO] Resolved code 49-9060 with code 49-9062 through BLS total employment data.
[INFO] Resolved code 51-2020 with code 51-2022 through BLS total employment data.
[INFO] Resolved code 51-2090 with code 51-2092 through BLS total employment data.
[INFO] Resolved code 51-3020 with code 51-3022 through BLS total employment data.
[INFO] Resolved code 51-4010 with code 51-4011 through BLS total employment data.
[INFO] Resolved code 51-4050 with code 51-4051 through BLS total employment data.
[INFO] Resolved code 51-4060 with code 51-4061 through BLS total employment data.
[INFO] Resolved code 51-4070 with code 51-4072 through BLS total employment data.
[INFO] Resolved code 51-4120 with code 51-4121 through BLS total employment data.
[INFO] Resolved code 51-6050 with code 51-6052 through BLS total employment data.
[INFO] Resolved code 51-7030 with code 51-7031 through BLS total employment data.
[INFO] Resolved code 51-8010 with code 51-8013 through BLS total employment data.
[INFO] Resolved code 51-8090 with code 51-8093 through BLS total employment data.
[INFO] Resolved code 51-9010 with code 51-9011 through BLS total employment data.
[INFO] Resolved code 51-9020 with code 51-9023 through BLS total employment data.
[INFO] Resolved code 51-9030 with code 51-9032 through BLS total employment data.
[INFO] Resolved code 51-9080 with code 51-9081 through BLS total employment data.
[INFO] Resolved code 51-9120 with code 51-9121 through BLS total employment data.
[INFO] Resolved code 53-1000 with code 53-1031 through BLS total employment data.
[INFO] Resolved code 53-2010 with code 53-2011 through BLS total employment data.
[INFO] Resolved code 53-2020 with code 53-2021 through BLS total employment data.
[INFO] Resolved code 53-3020 with code 53-3022 through BLS total employment data.
[INFO] Resolved code 53-3030 with code 53-3032 through BLS total employment data.
[INFO] Resolved code 53-4010 with code 53-4011 through BLS total employment data.
[INFO] Resolved code 53-5020 with code 53-5021 through BLS total employment data.
[INFO] Resolved code 53-7030 with code 53-7032 through BLS total employment data.
[INFO] Resolved code 53-7070 with code 53-7073 through BLS total employment data.

In [24]:
# Get codes that must be manually resolved
for key,candidates in unresolved.items():
    print(f"[WARNING] Must be resolved manually for SOC 2010 Code: {key}")
    print(f"[INFO] Corresponding candidates: {candidates}\n")

# Building SOC 2010 to O*NET 2019 Crosswalk

In [25]:
missing_soc2018 = set(soc2010_to_soc2018.values()) - set(soc2018_to_onet2019.keys())
if missing_soc2018:
    print("[WARNING] There are missing SOC 2018 Codes",
          "which must be fixed before we build a mapping",
          "between SOC 2010 and O*NET-SOC 2019")

soc2010_to_onet2019 = {}
for soc2010,soc2018 in soc2010_to_soc2018.items():
    onet2019 = soc2018_to_onet2019[soc2018]
    soc2010_to_onet2019[soc2010] = onet2019

# Building 2010 Census Code to 2010 SOC Mapping

In [26]:
df_gss_soc.tail(20)

,Occupation Title,2010 Census Code,2010 SOC Code
515,Bridge and lock tenders,9340,53-6011
516,Parking lot attendants,9350,53-6021
517,Automotive and watercraft service attendants,9360,53-6031
518,Transportation inspectors,9410,53-6051
519,"Transportation attendants, except flight atten...",9415,53-6061
520,Other transportation workers,9420,"53-6041, 53-6099"
521,Conveyor operators and tenders,9500,53-7011
522,Crane and tower operators,9510,53-7021
523,"Dredge, excavating, and loading machine operators",9520,53-7030
524,Hoist and winch operators,9560,53-7041
525,Industrial truck and tractor operators,9600,53-7051
526,Cleaners of vehicles and equipment,9610,53-7061
527,"Laborers and freight, stock, and material move...",9620,53-7062
528,Machine feeders and offbearers,9630,53-7063
529,"Packers and packagers, hand",9640,53-7064
530,Pumping station operators,9650,53-7070
531,Refuse and recyclable material collectors,9720,53-7081
532,Mine shuttle car operators,9730,53-7111
533,"Tank car, truck, and ship loaders",9740,53-7121
534,"Material moving workers, all other",9750,53-7199

In [27]:
df_gss_soc["2010 Census Code"].duplicated(keep=False).sum()

np.int64(0)

In [28]:
df_gss_soc["2010 SOC Code"].duplicated(keep=False).sum()

np.int64(0)

### Observations: Building 2010 Census Code to 2010 SOC Mapping
So it looks like this DataFrame is horizontally expanded, where some 2010 Census Codes will be associated with multiple 2010 SOC codes, denoted by the CSV in the `2010 SOC Code` column.

I'll handle this in a similar way as above, where I will use exact job title matching and BLS data to determine which candidate is the most fitting for 2010 Census Codes with multiple 2010 SOC Code candidates.

In [29]:
# One-to-ones only
census2010_to_soc2010 = {census2010:soc2010 for census2010,soc2010 
                         in zip(df_gss_soc["2010 Census Code"],
                                df_gss_soc["2010 SOC Code"]) 
                            if len(soc2010.split(",")) == 1}

# One-to-many only
ambiguous_census2010_to_soc2010 = {census2010:soc2010.replace(" ", "").split(",") 
                                   for census2010,soc2010 
                                   in zip(df_gss_soc["2010 Census Code"],
                                          df_gss_soc["2010 SOC Code"]) 
                                   if len(soc2010.replace(" ", "").split(",")) > 1}

In [30]:
# Check that dictionaries are disjoint and fully covering 
overlap = set(census2010_to_soc2010.keys()) & set(ambiguous_census2010_to_soc2010.keys())
disjoint = (len(overlap) == 0)

union = set(census2010_to_soc2010.keys()) | set(ambiguous_census2010_to_soc2010.keys())
fully_covers = union == set(df_gss_soc["2010 Census Code"].unique())
disjoint_and_fully_covers = disjoint and fully_covers

if not disjoint_and_fully_covers:
    print("[WARNING] Dictionaries are not disjoint or don't have full coverage of all possible 2010 Census Codes")
else:
    print("[INFO] Dictionaries are disjoint and have full coverage of all possible 2010 Census Codes")

[INFO] Dictionaries are disjoint and have full coverage of all possible 2010 Census Codes

In [31]:
# Find any with exact job title matches
resolved = set()
for census2010, soc2010_cands in ambiguous_census2010_to_soc2010.items():
    census_mask = df_gss_soc["2010 Census Code"] == census2010
    census_title = (df_gss_soc[census_mask]["Occupation Title"].unique()[0])
    for c in soc2010_cands:
        c_mask = df_bls["occ code"] == c
        c_title = df_bls[c_mask]["occ title"].unique()[0]
        if c_title == census_title:
            census2010_to_soc2010[census2010] = c
            resolved.add(census2010)
            print(f"[INFO] Resolved {census2010} with {c} through exact job title matching")

while resolved:
    code = resolved.pop()
    del ambiguous_census2010_to_soc2010[code]

In [32]:
# Use BLS employment data to choose candidate with the most employed
for census2010, soc2010_cands in ambiguous_census2010_to_soc2010.items():
    soc2010 = tiebreaker(soc2010_cands, df_bls, 
                         occ_code="occ code", 
                         tot_emp="tot_emp")
    if soc2010 is None:
        continue
    census2010_to_soc2010[census2010] = soc2010
    resolved.add(census2010)
    print(f"[INFO] Resolved {census2010} with {soc2010} through BLS employment data")

while resolved:
    code = resolved.pop()
    del ambiguous_census2010_to_soc2010[code]

[INFO] Resolved 1020 with 15-1132 through BLS employment data
[INFO] Resolved 2025 with 21-1099 through BLS employment data
[INFO] Resolved 2550 with 25-9031 through BLS employment data
[INFO] Resolved 3655 with 31-9099 through BLS employment data
[INFO] Resolved 3955 with 33-9099 through BLS employment data
[INFO] Resolved 4220 with 37-2011 through BLS employment data
[INFO] Resolved 4460 with 39-4021 through BLS employment data
[INFO] Resolved 6940 with 47-5099 through BLS employment data
[INFO] Resolved 7100 with 49-2094 through BLS employment data
[INFO] Resolved 7330 with 49-9041 through BLS employment data
[INFO] Resolved 7630 with 49-9099 through BLS employment data
[INFO] Resolved 9260 with 53-4041 through BLS employment data
[INFO] Resolved 9420 with 53-6099 through BLS employment data

In [33]:
# Get codes that need to be manually resolved
for key,val in ambiguous_census2010_to_soc2010.items():
    print(f"[WARNING] Need to resolve census code {key}")
    print(f"[WARNING] Candidates are: {val}")
    print()

# Building 2010 Census Code to O*NET-SOC 2019 Crosswalk

In [34]:
set(census2010_to_soc2010.values()) - set(soc2010_to_onet2019.keys())

set()

In [35]:
census2010_to_onet2019 = {}
for census2010, soc2010 in census2010_to_soc2010.items():
    onet_2019 = soc2010_to_onet2019[soc2010]
    census2010_to_onet2019[census2010] = onet_2019

census2010_to_onet2019

{10: '11-1011.00',
 20: '11-1021.00',
 30: '11-1031.00',
 40: '11-2011.00',
 50: '11-2022.00',
 60: '11-2032.00',
 100: '11-3012.00',
 110: '11-3021.00',
 120: '11-3031.00',
 135: '11-3111.00',
 136: '11-3121.00',
 137: '11-3131.00',
 140: '11-3051.00',
 150: '11-3061.00',
 160: '11-3071.00',
 205: '11-9013.00',
 220: '11-9021.00',
 230: '11-9032.00',
 300: '11-9041.00',
 310: '11-9051.00',
 325: '11-9171.00',
 330: '11-9071.00',
 340: '11-9081.00',
 350: '11-9111.00',
 360: '11-9121.00',
 400: '11-9131.00',
 410: '11-9141.00',
 420: '11-9151.00',
 425: '11-9161.00',
 430: '13-1082.00',
 500: '13-1011.00',
 510: '13-1021.00',
 520: '13-1022.00',
 530: '13-1023.00',
 540: '13-1031.00',
 565: '13-1041.00',
 600: '13-1051.00',
 630: '13-1071.00',
 640: '13-1141.00',
 650: '13-1151.00',
 700: '13-1081.00',
 710: '13-1111.00',
 725: '13-1121.00',
 726: '13-1131.00',
 735: '13-1161.00',
 740: '13-1199.00',
 800: '13-2011.00',
 810: '13-2023.00',
 820: '13-2031.00',
 830: '13-2041.00',
 840: '13-2051.00',
 850: '13-2052.00',
 860: '13-2053.00',
 900: '13-2061.00',
 910: '13-2072.00',
 930: '13-2081.00',
 940: '13-2082.00',
 950: '13-2099.00',
 1005: '15-1221.00',
 1006: '15-1211.00',
 1007: '15-1212.00',
 1010: '15-1251.00',
 1030: '15-1254.00',
 1050: '15-1232.00',
 1060: '15-1242.00',
 1105: '15-1244.00',
 1106: '15-1241.00',
 1107: '13-1082.00',
 1200: '15-2011.00',
 1210: '15-2021.00',
 1220: '15-2031.00',
 1230: '15-2041.00',
 1240: '15-2051.00',
 1300: '17-1011.00',
 1310: '17-1022.00',
 1320: '17-2011.00',
 1330: '17-2021.00',
 1340: '17-2031.00',
 1350: '17-2041.00',
 1360: '17-2051.00',
 1400: '17-2061.00',
 1410: '17-2071.00',
 1420: '17-2081.00',
 1430: '17-2112.00',
 1440: '17-2121.00',
 1450: '17-2131.00',
 1460: '17-2141.00',
 1500: '17-2151.00',
 1510: '17-2161.00',
 1520: '17-2171.00',
 1530: '17-2199.00',
 1540: '17-3011.00',
 1550: '17-3023.00',
 1560: '17-3031.00',
 1600: '19-1013.00',
 1610: '19-1029.00',
 1640: '19-1031.00',
 1650: '19-1042.00',
 1660: '19-1099.00',
 1700: '19-2012.00',
 1710: '19-2021.00',
 1720: '19-2031.00',
 1740: '19-2041.00',
 1760: '19-2099.00',
 1800: '19-3011.00',
 1815: '19-3022.00',
 1820: '19-3034.00',
 1830: '19-3041.00',
 1840: '19-3051.00',
 1860: '19-3099.00',
 1900: '19-4012.00',
 1910: '19-4021.00',
 1920: '19-4031.00',
 1930: '19-4043.00',
 1940: '19-4051.00',
 1950: '19-4061.00',
 1965: '19-4099.00',
 2000: '21-1012.00',
 2010: '21-1021.00',
 2015: '21-1092.00',
 2016: '21-1093.00',
 2040: '21-2011.00',
 2050: '21-2021.00',
 2060: '21-2099.00',
 2100: '23-1011.00',
 2105: '23-1012.00',
 2110: '23-1023.00',
 2145: '23-2011.00',
 2160: '23-2093.00',
 2200: '25-1071.00',
 2300: '25-2011.00',
 2310: '25-2021.00',
 2320: '25-2031.00',
 2330: '25-2056.00',
 2340: '25-3021.00',
 2400: '25-4012.00',
 2430: '25-4022.00',
 2440: '25-4031.00',
 2540: '25-9042.00',
 2600: '27-1011.00',
 2630: '27-1024.00',
 2700: '27-2011.00',
 2710: '27-2012.00',
 2720: '27-2022.00',
 2740: '27-2031.00',
 2750: '27-2042.00',
 2760: '27-2099.00',
 2800: '27-3011.00',
 2810: '27-3023.00',
 2825: '27-3031.00',
 2830: '27-3041.00',
 2840: '27-3042.00',
 2850: '27-3043.00',
 2860: '27-3091.00',
 2900: '27-4011.00',
 2910: '27-4021.00',
 2920: '27-4032.00',
 2960: '27-4099.00',
 3000: '29-1011.00',
 3010: '29-1021.00',
 3030: '29-1031.00',
 3040: '29-1041.00',
 3050: '29-1051.00',
 3060: '29-1229.00',
 3110: '29-1071.00',
 3120: '29-1081.00',
 3140: '29-1181.00',
 3150: '29-1122.00',
 3160: '29-1123.00',
 3200: '29-1124.00',
 3210: '29-1125.00',
 3220: '29-1126.00',
 3230: '29-1127.00',
 3235: '29-1128.00',
 3245: '29-1129.00',
 3250: '29-1131.00',
 3255: '29-1141.00',
 3256: '29-1151.00',
 3257: '29-1161.00',
 3258: '29-1171.00',
 3260: '29-1299.00',
 3300: '29-2011.00',
 3310: '29-1292.00',
 3320: '29-2034.00',
 3400: '29-2042.00',
 3420: '29-2052.00',
 3500: '29-2061.00',
 3510: '29-2072.00',
 3520: '29-2081.00',
 3535: '29-2099.00',
 3540: '19-5011.00',
 3600: '31-1131.00',
 3610: '31-2011.00',
 3620: '31-2021.00',
 3630: '31-9011.00',
 3640: '31-9091.00',
 3645: '31-9092.00',
 3646: '31-9094.00',
 3647: '31-9095.00',
 3648: '31-9096.00',
 3649: '31-9097.00',
 3700: '33-1011.00',
 3710: '33-1012.00',
 3720: '33-1021.00',
 3730: '33-1091.00',
 3740: '33-2011.00',
 3750: '33-2021.00',
 3800: '33-3012.00',
 3820: '33-3021.00',
 3830: '33-3031.00',
 3840: '33-3041.00',
 3850: '33-3051.00',
 3860: '33-3052.00',
 3900: '33-9011.00',
 3910: '33-9021.00',
 3930: '33-9032.00',
 3940: '33-9091.00',
 3945: '33-9093.00',
 4000: '35-1011.00',
 4010: '35-1012.00',
 4020: '35-2014.00',
 4030: '35-2021.00',
 4040: '35-3011.00',
 4050: '35-3023.00',
 4060: '35-3023.00',
 4110: '35-3031.00',
 4120: '35-3041.00',
 4130: '35-9011.00',
 4140: '35-9021.00',
 4150: '35-9031.00',
 4160: '35-9099.00',
 4200: '37-1011.00',
 4210: '37-1012.00',
 4230: '37-2012.00',
 4240: '37-2021.00',
 4250: '37-3011.00',
 4300: '39-1013.00',
 4320: '39-1022.00',
 4340: '39-2011.00',
 4350: '39-2021.00',
 4400: '39-3011.00',
 4410: '39-3021.00',
 4420: '39-3031.00',
 4430: '39-3091.00',
 4465: '39-4031.00',
 4500: '39-5011.00',
 4510: '39-5012.00',
 4520: '39-5092.00',
 4530: '39-6011.00',
 4540: '39-7011.00',
 4600: '39-9011.00',
 4610: '31-1122.00',
 4620: '39-9032.00',
 4640: '39-9041.00',
 4650: '39-9099.00',
 4700: '41-1011.00',
 4710: '41-1012.00',
 4720: '41-2011.00',
 4740: '41-2021.00',
 4750: '41-2022.00',
 4760: '41-2031.00',
 4800: '41-3011.00',
 4810: '41-3021.00',
 4820: '41-3031.00',
 4830: '41-3041.00',
 4840: '41-3091.00',
 4850: '41-4012.00',
 4900: '41-9011.00',
 4920: '41-9022.00',
 4930: '41-9031.00',
 4940: '41-9041.00',
 4950: '41-9091.00',
 4965: '41-9099.00',
 5000: '43-1011.00',
 5010: '43-2011.00',
 5020: '43-2021.00',
 5030: '43-2099.00',
 5100: '43-3011.00',
 5110: '43-3021.00',
 5120: '43-3031.00',
 5130: '43-3041.00',
 5140: '43-3051.00',
 5150: '43-3061.00',
 5160: '43-3071.00',
 5165: '43-3099.00',
 5200: '43-4011.00',
 5210: '43-4021.00',
 5220: '43-4031.00',
 5230: '43-4041.00',
 5240: '43-4051.00',
 5250: '43-4061.00',
 5260: '43-4071.00',
 5300: '43-4081.00',
 5310: '43-4111.00',
 5320: '43-4121.00',
 5330: '43-4131.00',
 5340: '43-4141.00',
 5350: '43-4151.00',
 5360: '43-4161.00',
 5400: '43-4171.00',
 5410: '43-4181.00',
 5420: '43-4199.00',
 5500: '43-5011.00',
 5510: '43-5021.00',
 5520: '43-5032.00',
 5530: '43-5041.00',
 5540: '43-5051.00',
 5550: '43-5052.00',
 5560: '43-5053.00',
 5600: '43-5061.00',
 5610: '43-5071.00',
 5620: '53-7065.00',
 5630: '43-5111.00',
 5700: '43-6014.00',
 5800: '15-1299.00',
 5810: '43-9021.00',
 5820: '43-9022.00',
 5830: '43-9031.00',
 5840: '43-9041.00',
 5850: '43-9051.00',
 5860: '43-9061.00',
 5900: '43-9071.00',
 5910: '43-9081.00',
 5920: '43-9111.00',
 5940: '43-9199.00',
 6005: '45-1011.00',
 6010: '45-2011.00',
 6020: '45-2021.00',
 6040: '45-2041.00',
 6050: '45-2092.00',
 6100: '45-3031.00',
 6110: '45-3031.00',
 6120: '45-4011.00',
 6130: '45-4022.00',
 6200: '47-1011.00',
 6210: '47-2011.00',
 6220: '47-2021.00',
 6230: '47-2031.00',
 6240: '47-2044.00',
 6250: '47-2051.00',
 6260: '47-2061.00',
 6300: '47-2071.00',
 6310: '47-2072.00',
 6320: '47-2073.00',
 6330: '47-2081.00',
 6355: '47-2111.00',
 6360: '47-2121.00',
 6400: '47-2131.00',
 6420: '47-2141.00',
 6430: '47-2142.00',
 6440: '47-2152.00',
 6460: '47-2161.00',
 6500: '47-2171.00',
 6515: '47-2181.00',
 6520: '47-2211.00',
 6530: '47-2221.00',
 6540: '47-2231.00',
 6600: '47-3013.00',
 6660: '47-4011.00',
 6700: '47-4021.00',
 6710: '47-4031.00',
 6720: '47-4041.00',
 6730: '47-4051.00',
 6740: '47-4061.00',
 6750: '47-4071.00',
 6765: '47-4099.00',
 6800: '47-5013.00',
 6820: '47-5023.00',
 6830: '47-5032.00',
 6840: '47-5041.00',
 6910: '47-5043.00',
 6920: '47-5071.00',
 6930: '47-5081.00',
 7000: '49-1011.00',
 7010: '49-2011.00',
 7020: '49-2022.00',
 7030: '49-2091.00',
 7040: '49-2092.00',
 7050: '49-2093.00',
 7110: '49-2096.00',
 7120: '49-2097.00',
 7130: '49-2098.00',
 7140: '49-3011.00',
 7150: '49-3021.00',
 7160: '49-3022.00',
 7200: '49-3023.00',
 7210: '49-3031.00',
 7220: '49-3042.00',
 7240: '49-3053.00',
 7260: '49-3093.00',
 7300: '49-9012.00',
 7315: '49-9021.00',
 7320: '49-9031.00',
 7340: '49-9071.00',
 7350: '49-9043.00',
 7360: '49-9044.00',
 7410: '49-9051.00',
 7420: '49-9052.00',
 7430: '49-9062.00',
 7440: '49-9081.00',
 7510: '49-9091.00',
 7520: '49-9092.00',
 7540: '49-9094.00',
 7550: '49-9095.00',
 7560: '49-9096.00',
 7600: '49-9097.00',
 7610: '49-9098.00',
 7700: '51-1011.00',
 7710: '51-2011.00',
 7720: '51-2022.00',
 7730: '51-2031.00',
 7740: '51-2041.00',
 7750: '51-2092.00',
 7800: '51-3011.00',
 7810: '51-3022.00',
 7830: '51-3091.00',
 7840: '51-3092.00',
 7850: '51-3093.00',
 7855: '51-3099.00',
 7900: '51-9161.00',
 7920: '51-4021.00',
 7930: '51-4022.00',
 7940: '51-4023.00',
 7950: '51-4031.00',
 7960: '51-4032.00',
 8000: '51-4033.00',
 8010: '51-4034.00',
 8020: '51-4035.00',
 8030: '51-4041.00',
 8040: '51-4051.00',
 8060: '51-4061.00',
 8100: '51-4072.00',
 8120: '51-4081.00',
 8130: '51-4111.00',
 8140: '51-4121.00',
 8150: '51-4191.00',
 8160: '51-4192.00',
 8200: '51-4193.00',
 8210: '51-4194.00',
 8220: '51-4199.00',
 8250: '51-5111.00',
 8255: '51-5112.00',
 8256: '51-5113.00',
 8300: '51-6011.00',
 8310: '51-6021.00',
 8320: '51-6031.00',
 8330: '51-6041.00',
 8340: '51-6042.00',
 8350: '51-6052.00',
 8360: '51-6061.00',
 8400: '51-6062.00',
 8410: '51-6063.00',
 8420: '51-6064.00',
 8430: '51-6091.00',
 8440: '51-6092.00',
 8450: '51-6093.00',
 8460: '51-6099.00',
 8500: '51-7011.00',
 8510: '51-7021.00',
 8520: '51-7031.00',
 8530: '51-7041.00',
 8540: '51-7042.00',
 8550: '51-7099.00',
 8600: '51-8013.00',
 8610: '51-8021.00',
 8620: '51-8031.00',
 8630: '51-8093.00',
 8640: '51-9011.00',
 8650: '51-9023.00',
 8710: '51-9032.00',
 8720: '51-9041.00',
 8730: '51-9051.00',
 8740: '51-9061.00',
 8750: '51-9071.00',
 8760: '51-9081.00',
 8800: '51-9111.00',
 8810: '51-9124.00',
 8830: '51-9151.00',
 8840: '51-9141.00',
 8850: '51-9191.00',
 8860: '51-9192.00',
 8900: '51-9193.00',
 8910: '51-9194.00',
 8920: '51-9195.00',
 8930: '51-9196.00',
 8940: '51-9197.00',
 8950: '51-9198.00',
 8965: '51-9199.00',
 9000: '53-1043.00',
 9030: '53-2011.00',
 9040: '53-2021.00',
 9050: '53-2031.00',
 9110: '53-3011.00',
 9120: '53-3051.00',
 9130: '53-3032.00',
 9140: '53-3053.00',
 9150: '53-3099.00',
 9200: '53-4011.00',
 9230: '53-4022.00',
 9240: '53-4031.00',
 9300: '53-5011.00',
 9310: '53-5021.00',
 9330: '53-5031.00',
 9340: '53-6011.00',
 9350: '53-6021.00',
 9360: '53-6031.00',
 9410: '53-6051.00',
 9415: '53-6061.00',
 9500: '53-7011.00',
 9510: '53-7021.00',
 9520: '47-5022.00',
 9560: '53-7041.00',
 9600: '53-7051.00',
 9610: '53-7061.00',
 9620: '53-7062.00',
 9630: '53-7063.00',
 9640: '53-7064.00',
 9650: '53-7073.00',
 9720: '53-7081.00',
 9730: '47-5044.00',
 9740: '53-7121.00',
 9750: '53-7199.00',
 1020: '15-1252.00',
 2025: '21-1099.00',
 2550: '25-9031.00',
 3655: '31-9099.00',
 3955: '33-9099.00',
 4220: '37-2011.00',
 4460: '39-4021.00',
 6940: '47-5099.00',
 7100: '49-2094.00',
 7330: '49-9041.00',
 7630: '49-9099.00',
 9260: '53-4041.00',
 9420: '53-6099.00'}

In [36]:
# Write our CSV
with open(crosswalk_dir + "census2010_to_onet2019.csv", mode="w", newline="") as file:
    writer = csv.writer(file)

    # CSV header
    writer.writerow(["2010 Census Code", 
                     "2010 Census Title", 
                     "O*NET-SOC 2019 Code", 
                     "O*NET-SOC 2019 Title"])
    
    # Write each key-value pair as a row
    for census2010, onet2019 in census2010_to_onet2019.items():
        census_mask = df_gss_soc["2010 Census Code"] == census2010
        census_title = df_gss_soc[census_mask]["Occupation Title"].unique()[0]

        onet_mask = df_onet2019_soc2018["O*NET-SOC 2019 Code"] == onet2019
        onet_title = df_onet2019_soc2018[onet_mask]["O*NET-SOC 2019 Title"].unique()[0]
        writer.writerow([census2010, census_title, onet2019, onet_title])

# ISCO 2008 to SOC 2010 mapping

In [37]:
df_isco_soc2010 = pd.read_csv(crosswalk_dir + "/ISCO_SOC_Crosswalk.csv", 
                              dtype={"ISCO-08 Code": str})
df_isco_soc2010 = df_isco_soc2010.astype(str)
df_isco_soc2010.head()

,ISCO-08 Code,ISCO-08 Title EN,part,2010 SOC Code,2010 SOC Title,Comment 8/17/11
0,0110,Commissioned armed forces officers,*,55-1011,Air Crew Officers,NaN
1,0110,Commissioned armed forces officers,*,55-1012,Aircraft Launch and Recovery Officers,NaN
2,0110,Commissioned armed forces officers,*,55-1013,Armored Assault Vehicle Officers,NaN
3,0110,Commissioned armed forces officers,*,55-1014,Artillery and Missile Officers,NaN
4,0110,Commissioned armed forces officers,*,55-1015,Command and Control Center Officers,NaN

In [38]:
df_isco_soc2010.drop(columns="Comment 8/17/11", inplace=True)
df_isco_soc2010.head()

,ISCO-08 Code,ISCO-08 Title EN,part,2010 SOC Code,2010 SOC Title
0,0110,Commissioned armed forces officers,*,55-1011,Air Crew Officers
1,0110,Commissioned armed forces officers,*,55-1012,Aircraft Launch and Recovery Officers
2,0110,Commissioned armed forces officers,*,55-1013,Armored Assault Vehicle Officers
3,0110,Commissioned armed forces officers,*,55-1014,Artillery and Missile Officers
4,0110,Commissioned armed forces officers,*,55-1015,Command and Control Center Officers

In [39]:
df_isco_soc2010["2010 SOC Code"] = df_isco_soc2010["2010 SOC Code"].str.strip()

In [40]:
# Split into ambiguous and unambiguous data frames
ambiguous_mask = df_isco_soc2010["ISCO-08 Code"].duplicated(keep=False)
df_isco_ambiguous = df_isco_soc2010[ambiguous_mask]
df_isco_unambiguous = df_isco_soc2010[~ambiguous_mask]

# Construct unambiguous dictionary
isco_to_soc2010 = {isco:soc for isco,soc 
                   in zip(df_isco_unambiguous["ISCO-08 Code"], 
                          df_isco_unambiguous["2010 SOC Code"])}

# Construct ambiguous dictionary
ambiguous_isco_to_soc2010 = {}
for idx, row in df_isco_ambiguous.iterrows():
    isco = row["ISCO-08 Code"]
    soc = row["2010 SOC Code"]
    ambiguous_isco_to_soc2010.setdefault(isco, []).append(soc)

In [41]:
# Try to resolve with exact job title match
resolved = set()
for isco, soc_cands in ambiguous_isco_to_soc2010.items():
    isco_mask = df_isco_ambiguous["ISCO-08 Code"] == isco
    isco_title = df_isco_ambiguous[isco_mask]["ISCO-08 Title EN"].unique()[0]

    for soc in soc_cands:
        soc_mask = df_isco_ambiguous["2010 SOC Code"] == soc
        soc_title = df_isco_ambiguous[soc_mask]["2010 SOC Title"].unique()[0]

        if isco_title == soc_title:
            isco_to_soc2010[isco] = soc
            resolved.add(isco)
            print(f"[INFO] Resolved {isco} with {soc} using job title matching")
            break

while resolved:
    isco = resolved.pop()
    del ambiguous_isco_to_soc2010[isco]

[INFO] Resolved 2113 with 19-2031 using job title matching

In [42]:
# Use BLS data to get the best candidate that maximizes coverage
for isco, soc_cands in ambiguous_isco_to_soc2010.items():
    soc2010 = tiebreaker(soc_cands, df_bls, occ_code="occ code", tot_emp="tot_emp")
    if soc2010 is None:
        continue
    isco_to_soc2010[isco] = soc2010
    resolved.add(isco)
    print(f"[INFO] Resolved {isco} with {soc2010} using BLS total employed data")

while resolved:
    isco = resolved.pop()
    del ambiguous_isco_to_soc2010[isco]

[INFO] Resolved 1112 with 11-1021 using BLS total employed data
[INFO] Resolved 1113 with 11-1011 using BLS total employed data
[INFO] Resolved 1114 with 11-1021 using BLS total employed data
[INFO] Resolved 1120 with 11-1021 using BLS total employed data
[INFO] Resolved 1212 with 11-3121 using BLS total employed data
[INFO] Resolved 1219 with 11-9199 using BLS total employed data
[INFO] Resolved 1221 with 11-2022 using BLS total employed data
[INFO] Resolved 1222 with 11-2031 using BLS total employed data
[INFO] Resolved 1223 with 11-9041 using BLS total employed data
[INFO] Resolved 1343 with 11-1021 using BLS total employed data
[INFO] Resolved 1345 with 11-9032 using BLS total employed data
[INFO] Resolved 1346 with 11-1021 using BLS total employed data
[INFO] Resolved 1431 with 11-9199 using BLS total employed data
[INFO] Resolved 2111 with 19-2012 using BLS total employed data
[INFO] Resolved 2114 with 19-2042 using BLS total employed data
[INFO] Resolved 2120 with 15-2031 using BLS total employed data
[INFO] Resolved 2131 with 19-1042 using BLS total employed data
[INFO] Resolved 2132 with 19-1013 using BLS total employed data
[INFO] Resolved 2133 with 19-2041 using BLS total employed data
[INFO] Resolved 2144 with 17-2141 using BLS total employed data
[INFO] Resolved 2146 with 17-2171 using BLS total employed data
[INFO] Resolved 2149 with 17-2199 using BLS total employed data
[INFO] Resolved 2152 with 17-2072 using BLS total employed data
[INFO] Resolved 2163 with 27-1021 using BLS total employed data
[INFO] Resolved 2165 with 17-1022 using BLS total employed data
[INFO] Resolved 2166 with 27-1024 using BLS total employed data
[INFO] Resolved 2211 with 29-1069 using BLS total employed data
[INFO] Resolved 2212 with 29-1069 using BLS total employed data
[INFO] Resolved 2221 with 29-1141 using BLS total employed data
[INFO] Resolved 2261 with 29-1021 using BLS total employed data
[INFO] Resolved 2263 with 29-9011 using BLS total employed data
[INFO] Resolved 2264 with 29-1123 using BLS total employed data
[INFO] Resolved 2266 with 29-1127 using BLS total employed data
[INFO] Resolved 2269 with 29-1122 using BLS total employed data
[INFO] Resolved 2310 with 25-1071 using BLS total employed data
[INFO] Resolved 2320 with 25-1194 using BLS total employed data
[INFO] Resolved 2341 with 25-2021 using BLS total employed data
[INFO] Resolved 2342 with 25-2011 using BLS total employed data
[INFO] Resolved 2352 with 25-2052 using BLS total employed data
[INFO] Resolved 2353 with 25-3021 using BLS total employed data
[INFO] Resolved 2355 with 25-3021 using BLS total employed data
[INFO] Resolved 2359 with 21-1012 using BLS total employed data
[INFO] Resolved 2411 with 13-2011 using BLS total employed data
[INFO] Resolved 2412 with 13-2051 using BLS total employed data
[INFO] Resolved 2413 with 13-2051 using BLS total employed data
[INFO] Resolved 2421 with 13-1111 using BLS total employed data
[INFO] Resolved 2423 with 13-1071 using BLS total employed data
[INFO] Resolved 2431 with 13-1161 using BLS total employed data
[INFO] Resolved 2433 with 41-4011 using BLS total employed data
[INFO] Resolved 2434 with 41-4011 using BLS total employed data
[INFO] Resolved 2511 with 15-1121 using BLS total employed data
[INFO] Resolved 2512 with 15-1132 using BLS total employed data
[INFO] Resolved 2529 with 15-1199 using BLS total employed data
[INFO] Resolved 2612 with 23-1023 using BLS total employed data
[INFO] Resolved 2621 with 25-4012 using BLS total employed data
[INFO] Resolved 2622 with 25-4021 using BLS total employed data
[INFO] Resolved 2632 with 19-3091 using BLS total employed data
[INFO] Resolved 2633 with 19-3099 using BLS total employed data
[INFO] Resolved 2634 with 19-3031 using BLS total employed data
[INFO] Resolved 2635 with 21-1021 using BLS total employed data
[INFO] Resolved 2636 with 21-2011 using BLS total employed data
[INFO] Resolved 2641 with 27-3041 using BLS total employed data
[INFO] Resolved 2642 with 27-3041 using BLS total employed data
[INFO] Resolved 2643 with 27-3091 using BLS total employed data
[INFO] Resolved 2651 with 27-1013 using BLS total employed data
[INFO] Resolved 2652 with 27-2042 using BLS total employed data
[INFO] Resolved 2653 with 27-2031 using BLS total employed data
[INFO] Resolved 2654 with 27-2012 using BLS total employed data
[INFO] Resolved 2656 with 27-3011 using BLS total employed data
[INFO] Resolved 3111 with 19-4099 using BLS total employed data
[INFO] Resolved 3112 with 47-4011 using BLS total employed data
[INFO] Resolved 3113 with 17-3023 using BLS total employed data
[INFO] Resolved 3115 with 17-3029 using BLS total employed data
[INFO] Resolved 3117 with 17-3029 using BLS total employed data
[INFO] Resolved 3118 with 17-3011 using BLS total employed data
[INFO] Resolved 3119 with 19-4099 using BLS total employed data
[INFO] Resolved 3131 with 51-1011 using BLS total employed data
[INFO] Resolved 3132 with 51-1011 using BLS total employed data
[INFO] Resolved 3134 with 51-8093 using BLS total employed data
[INFO] Resolved 3141 with 19-4021 using BLS total employed data
[INFO] Resolved 3151 with 53-1031 using BLS total employed data
[INFO] Resolved 3152 with 53-1031 using BLS total employed data
[INFO] Resolved 3153 with 53-1031 using BLS total employed data
[INFO] Resolved 3154 with 53-1031 using BLS total employed data
[INFO] Resolved 3211 with 29-2034 using BLS total employed data
[INFO] Resolved 3212 with 29-2011 using BLS total employed data
[INFO] Resolved 3214 with 51-9081 using BLS total employed data
[INFO] Resolved 3240 with 29-2056 using BLS total employed data
[INFO] Resolved 3251 with 31-9091 using BLS total employed data
[INFO] Resolved 3255 with 31-9011 using BLS total employed data
[INFO] Resolved 3256 with 31-9092 using BLS total employed data
[INFO] Resolved 3257 with 53-1031 using BLS total employed data
[INFO] Resolved 3259 with 29-1126 using BLS total employed data
[INFO] Resolved 3311 with 41-3031 using BLS total employed data
[INFO] Resolved 3312 with 13-2072 using BLS total employed data
[INFO] Resolved 3314 with 19-4061 using BLS total employed data
[INFO] Resolved 3315 with 13-1031 using BLS total employed data
[INFO] Resolved 3321 with 41-3021 using BLS total employed data
[INFO] Resolved 3322 with 41-3099 using BLS total employed data
[INFO] Resolved 3323 with 13-1023 using BLS total employed data
[INFO] Resolved 3324 with 41-3031 using BLS total employed data
[INFO] Resolved 3331 with 43-5071 using BLS total employed data
[INFO] Resolved 3333 with 13-1071 using BLS total employed data
[INFO] Resolved 3334 with 41-1012 using BLS total employed data
[INFO] Resolved 3339 with 13-1199 using BLS total employed data
[INFO] Resolved 3343 with 43-6011 using BLS total employed data
[INFO] Resolved 3344 with 43-6013 using BLS total employed data
[INFO] Resolved 3351 with 33-3051 using BLS total employed data
[INFO] Resolved 3353 with 13-1041 using BLS total employed data
[INFO] Resolved 3354 with 13-1041 using BLS total employed data
[INFO] Resolved 3355 with 33-3021 using BLS total employed data
[INFO] Resolved 3411 with 23-2011 using BLS total employed data
[INFO] Resolved 3422 with 27-2022 using BLS total employed data
[INFO] Resolved 3423 with 39-9031 using BLS total employed data
[INFO] Resolved 3432 with 27-1026 using BLS total employed data
[INFO] Resolved 3433 with 25-4031 using BLS total employed data
[INFO] Resolved 3434 with 35-1012 using BLS total employed data
[INFO] Resolved 3435 with 27-3099 using BLS total employed data
[INFO] Resolved 3514 with 15-1142 using BLS total employed data
[INFO] Resolved 3521 with 27-4011 using BLS total employed data
[INFO] Resolved 4110 with 43-9061 using BLS total employed data
[INFO] Resolved 4211 with 43-3071 using BLS total employed data
[INFO] Resolved 4212 with 39-3011 using BLS total employed data
[INFO] Resolved 4213 with 41-9099 using BLS total employed data
[INFO] Resolved 4214 with 43-3011 using BLS total employed data
[INFO] Resolved 4221 with 41-1012 using BLS total employed data
[INFO] Resolved 4222 with 43-4051 using BLS total employed data
[INFO] Resolved 4223 with 43-2011 using BLS total employed data
[INFO] Resolved 4224 with 43-4081 using BLS total employed data
[INFO] Resolved 4225 with 43-4171 using BLS total employed data
[INFO] Resolved 4229 with 43-4199 using BLS total employed data
[INFO] Resolved 4311 with 43-3031 using BLS total employed data
[INFO] Resolved 4312 with 43-9041 using BLS total employed data
[INFO] Resolved 4321 with 43-5081 using BLS total employed data
[INFO] Resolved 4411 with 43-4121 using BLS total employed data
[INFO] Resolved 4412 with 43-5052 using BLS total employed data
[INFO] Resolved 4414 with 39-9021 using BLS total employed data
[INFO] Resolved 4415 with 43-4071 using BLS total employed data
[INFO] Resolved 4419 with 43-9199 using BLS total employed data
[INFO] Resolved 5111 with 53-1031 using BLS total employed data
[INFO] Resolved 5112 with 53-1031 using BLS total employed data
[INFO] Resolved 5113 with 39-1021 using BLS total employed data
[INFO] Resolved 5120 with 35-2014 using BLS total employed data
[INFO] Resolved 5131 with 35-3031 using BLS total employed data
[INFO] Resolved 5141 with 39-5012 using BLS total employed data
[INFO] Resolved 5142 with 39-5012 using BLS total employed data
[INFO] Resolved 5152 with 37-1011 using BLS total employed data
[INFO] Resolved 5162 with 39-9021 using BLS total employed data
[INFO] Resolved 5163 with 39-4021 using BLS total employed data
[INFO] Resolved 5164 with 39-1021 using BLS total employed data
[INFO] Resolved 5169 with 35-9031 using BLS total employed data
[INFO] Resolved 5169  with 39-9032 using BLS total employed data
[INFO] Resolved 5212 with 35-3041 using BLS total employed data
[INFO] Resolved 5223 with 41-2031 using BLS total employed data
[INFO] Resolved 5230 with 41-2011 using BLS total employed data
[INFO] Resolved 5245 with 53-1031 using BLS total employed data
[INFO] Resolved 5246 with 35-3021 using BLS total employed data
[INFO] Resolved 5249 with 41-2021 using BLS total employed data
[INFO] Resolved 5311 with 39-9011 using BLS total employed data
[INFO] Resolved 5321 with 31-1014 using BLS total employed data
[INFO] Resolved 5322 with 39-9021 using BLS total employed data
[INFO] Resolved 5329 with 31-9091 using BLS total employed data
[INFO] Resolved 5411 with 33-2011 using BLS total employed data
[INFO] Resolved 5412 with 33-3051 using BLS total employed data
[INFO] Resolved 5413 with 33-3012 using BLS total employed data
[INFO] Resolved 5414 with 33-9032 using BLS total employed data
[INFO] Resolved 5419 with 33-9099 using BLS total employed data
[INFO] Resolved 6111 with 45-2091 using BLS total employed data
[INFO] Resolved 6112 with 45-2091 using BLS total employed data
[INFO] Resolved 6113 with 37-1012 using BLS total employed data
[INFO] Resolved 6114 with 45-2091 using BLS total employed data
[INFO] Resolved 6121 with 45-1011 using BLS total employed data
[INFO] Resolved 6122 with 45-1011 using BLS total employed data
[INFO] Resolved 6123 with 45-1011 using BLS total employed data
[INFO] Resolved 6129 with 45-1011 using BLS total employed data
[INFO] Resolved 6130 with 45-2091 using BLS total employed data
[INFO] Resolved 6210 with 45-4022 using BLS total employed data
[INFO] Resolved 6221 with 45-1011 using BLS total employed data
[INFO] Resolved 6222 with 45-1011 using BLS total employed data
[INFO] Resolved 6223 with 45-1011 using BLS total employed data
[INFO] Resolved 6224 with 45-1011 using BLS total employed data
[INFO] Resolved 6330 with 45-2092 using BLS total employed data
[INFO] Resolved 6340 with 45-3011 using BLS total employed data
[INFO] Resolved 7112 with 47-2021 using BLS total employed data
[INFO] Resolved 7113 with 47-2022 using BLS total employed data
[INFO] Resolved 7114 with 47-2051 using BLS total employed data
[INFO] Resolved 7119 with 47-4041 using BLS total employed data
[INFO] Resolved 7122 with 47-2044 using BLS total employed data
[INFO] Resolved 7123 with 47-2081 using BLS total employed data
[INFO] Resolved 7124 with 47-2131 using BLS total employed data
[INFO] Resolved 7126 with 47-2152 using BLS total employed data
[INFO] Resolved 7127 with 49-1011 using BLS total employed data
[INFO] Resolved 7131 with 47-2141 using BLS total employed data
[INFO] Resolved 7132 with 51-9121 using BLS total employed data
[INFO] Resolved 7211 with 51-4072 using BLS total employed data
[INFO] Resolved 7212 with 51-4121 using BLS total employed data
[INFO] Resolved 7213 with 47-2211 using BLS total employed data
[INFO] Resolved 7214 with 51-2041 using BLS total employed data
[INFO] Resolved 7221 with 51-4199 using BLS total employed data
[INFO] Resolved 7222 with 51-4111 using BLS total employed data
[INFO] Resolved 7223 with 51-4041 using BLS total employed data
[INFO] Resolved 7224 with 51-9022 using BLS total employed data
[INFO] Resolved 7231 with 49-3023 using BLS total employed data
[INFO] Resolved 7232 with 49-1011 using BLS total employed data
[INFO] Resolved 7233 with 49-1011 using BLS total employed data
[INFO] Resolved 7234 with 49-1011 using BLS total employed data
[INFO] Resolved 7311 with 49-1011 using BLS total employed data
[INFO] Resolved 7312 with 49-1011 using BLS total employed data
[INFO] Resolved 7314 with 51-9195 using BLS total employed data
[INFO] Resolved 7315 with 51-9195 using BLS total employed data
[INFO] Resolved 7316 with 51-9123 using BLS total employed data
[INFO] Resolved 7317 with 51-7099 using BLS total employed data
[INFO] Resolved 7321 with 51-5111 using BLS total employed data
[INFO] Resolved 7411 with 47-2111 using BLS total employed data
[INFO] Resolved 7412 with 49-1011 using BLS total employed data
[INFO] Resolved 7413 with 49-1011 using BLS total employed data
[INFO] Resolved 7421 with 49-1011 using BLS total employed data
[INFO] Resolved 7422 with 49-1011 using BLS total employed data
[INFO] Resolved 7511 with 51-3022 using BLS total employed data
[INFO] Resolved 7513 with 51-3092 using BLS total employed data
[INFO] Resolved 7514 with 51-3099 using BLS total employed data
[INFO] Resolved 7515 with 45-2041 using BLS total employed data
[INFO] Resolved 7516 with 51-9041 using BLS total employed data
[INFO] Resolved 7521 with 51-9051 using BLS total employed data
[INFO] Resolved 7522 with 51-7011 using BLS total employed data
[INFO] Resolved 7532 with 51-6062 using BLS total employed data
[INFO] Resolved 7533 with 51-6041 using BLS total employed data
[INFO] Resolved 7535 with 45-2041 using BLS total employed data
[INFO] Resolved 7544 with 37-1012 using BLS total employed data
[INFO] Resolved 7549 with 27-1023 using BLS total employed data
[INFO] Resolved 8111 with 53-7032 using BLS total employed data
[INFO] Resolved 8112 with 51-9021 using BLS total employed data
[INFO] Resolved 8113 with 47-5071 using BLS total employed data
[INFO] Resolved 8114 with 51-9023 using BLS total employed data
[INFO] Resolved 8121 with 51-4021 using BLS total employed data
[INFO] Resolved 8122 with 51-9121 using BLS total employed data
[INFO] Resolved 8131 with 51-9011 using BLS total employed data
[INFO] Resolved 8141 with 51-9041 using BLS total employed data
[INFO] Resolved 8142 with 51-4031 using BLS total employed data
[INFO] Resolved 8143 with 51-9196 using BLS total employed data
[INFO] Resolved 8160 with 51-3092 using BLS total employed data
[INFO] Resolved 8171 with 51-9196 using BLS total employed data
[INFO] Resolved 8181 with 51-9023 using BLS total employed data
[INFO] Resolved 8189 with 53-7011 using BLS total employed data
[INFO] Resolved 8211 with 51-2031 using BLS total employed data
[INFO] Resolved 8212 with 51-2022 using BLS total employed data
[INFO] Resolved 8219 with 51-2092 using BLS total employed data
[INFO] Resolved 8311 with 53-1031 using BLS total employed data
[INFO] Resolved 8312 with 53-1031 using BLS total employed data
[INFO] Resolved 8321 with 53-1031 using BLS total employed data
[INFO] Resolved 8322 with 53-3033 using BLS total employed data
[INFO] Resolved 8331 with 53-3022 using BLS total employed data
[INFO] Resolved 8332 with 53-3032 using BLS total employed data
[INFO] Resolved 8341 with 45-2091 using BLS total employed data
[INFO] Resolved 8342 with 47-2073 using BLS total employed data
[INFO] Resolved 8343 with 39-3091 using BLS total employed data
[INFO] Resolved 8344 with 53-7051 using BLS total employed data
[INFO] Resolved 8350 with 53-5011 using BLS total employed data
[INFO] Resolved 9112 with 37-2011 using BLS total employed data
[INFO] Resolved 9129 with 47-4071 using BLS total employed data
[INFO] Resolved 9211 with 45-2092 using BLS total employed data
[INFO] Resolved 9212 with 45-2093 using BLS total employed data
[INFO] Resolved 9213 with 45-2092 using BLS total employed data
[INFO] Resolved 9214 with 37-3011 using BLS total employed data
[INFO] Resolved 9215 with 45-4011 using BLS total employed data
[INFO] Resolved 9216 with 45-2093 using BLS total employed data
[INFO] Resolved 9311 with 47-5081 using BLS total employed data
[INFO] Resolved 9312 with 47-4051 using BLS total employed data
[INFO] Resolved 9313 with 47-2061 using BLS total employed data
[INFO] Resolved 9329 with 53-7062 using BLS total employed data
[INFO] Resolved 9331 with 43-5021 using BLS total employed data
[INFO] Resolved 9332 with 53-6099 using BLS total employed data
[INFO] Resolved 9333 with 53-7062 using BLS total employed data
[INFO] Resolved 9411 with 35-2011 using BLS total employed data
[INFO] Resolved 9412 with 35-2021 using BLS total employed data
[INFO] Resolved 9611 with 53-1031 using BLS total employed data
[INFO] Resolved 9621 with 43-5021 using BLS total employed data
[INFO] Resolved 9622 with 49-9071 using BLS total employed data
[INFO] Resolved 9623 with 43-5041 using BLS total employed data
[INFO] Resolved 9629 with 39-3091 using BLS total employed data

In [43]:
# Print warnings
for key,val in ambiguous_isco_to_soc2010.items():
    print(f"[WARNING] Must resolve ISCO Code {key} manually")
    print(f"[WARNING] Candidates are: {val}")
    print()

[WARNING] Must resolve ISCO Code 0110 manually
[WARNING] Candidates are: ['55-1011', '55-1012', '55-1013', '55-1014', '55-1015', '55-1016', '55-1017', '55-1019']

[WARNING] Must resolve ISCO Code 0210 manually
[WARNING] Candidates are: ['55-2011', '55-2012', '55-2013']

[WARNING] Must resolve ISCO Code 0310 manually
[WARNING] Candidates are: ['55-3011', '55-3012', '55-3013', '55-3014', '55-3015', '55-3016', '55-3017', '55-3018', '55-3019']

In [44]:
# Manually resolve
isco_to_soc2010["0110"] = "55-1016"
isco_to_soc2010["0210"] = "55-2013"
isco_to_soc2010["0310"] = "55-3016"

# Building ISCO 2008 to O*NET-SOC 2019 Crosswalk

In [45]:
# Construct our map
isco_to_onet2019 = {}
for isco, soc2010 in isco_to_soc2010.items():
    soc2018 = soc2010_to_soc2018[soc2010]
    onet_2019 = soc2018_to_onet2019[soc2018]
    isco_to_onet2019[isco] = onet_2019

isco_to_onet2019

{'1111': '11-1031.00',
 '1211': '11-3031.00',
 '1213': '13-1082.00',
 '1311': '11-9013.00',
 '1312': '11-9013.00',
 '1321': '11-3051.00',
 '1322': '13-1082.00',
 '1323': '11-9021.00',
 '1324': '11-3071.00',
 '1330': '11-3021.00',
 '1341': '11-9031.00',
 '1342': '11-9111.00',
 '1344': '11-9151.00',
 '1349': '13-1082.00',
 '1411': '11-9081.00',
 '1412': '11-9051.00',
 '1420': '11-1021.00',
 '1439': '13-1082.00',
 '211': '19-2099.00',
 '2112': '19-2021.00',
 '2141': '17-2112.00',
 '2142': '17-2051.00',
 '2143': '17-2081.00',
 '2145': '17-2041.00',
 '2151': '17-2071.00',
 '2153': '17-2072.00',
 '2161': '17-1011.00',
 '2162': '17-1012.00',
 '2164': '19-3051.00',
 '2222': '29-1161.00',
 '2230': '29-1299.00',
 '2240': '29-1071.00',
 '2250': '29-1131.00',
 '2262': '29-1051.00',
 '2265': '29-1031.00',
 '2267': '29-1041.00',
 '2330': '25-2031.00',
 '2351': '25-9031.00',
 '2354': '25-3021.00',
 '2356': '13-1151.00',
 '2422': '13-1199.00',
 '2424': '13-1151.00',
 '2432': '27-3031.00',
 '2513': '15-1254.00',
 '2514': '15-1251.00',
 '2519': '13-1082.00',
 '2521': '15-1242.00',
 '2522': '15-1244.00',
 '2523': '15-1241.00',
 '2611': '23-1011.00',
 '2619': '23-1022.00',
 '2631': '19-3011.00',
 '2655': '27-2011.00',
 '2659': '27-2099.00',
 '3114': '17-3023.00',
 '3116': '17-3029.00',
 '3121': '47-1011.00',
 '3122': '51-1011.00',
 '3123': '47-1011.00',
 '3133': '51-8091.00',
 '3135': '51-4051.00',
 '3139': '51-9162.00',
 '3142': '19-4012.00',
 '3143': '19-4071.00',
 '315': '53-2022.00',
 '3155': '17-3023.00',
 '3213': '29-2052.00',
 '3221': '29-2061.00',
 '3222': '29-9099.00',
 '3230': '29-9099.00',
 '3252': '29-2072.00',
 '3253': '21-1094.00',
 '3254': '29-2081.00',
 '3258': '29-2042.00',
 '3313': '43-3031.00',
 '3322 ': '41-4012.00',
 '3332': '13-1121.00',
 '3341': '43-1011.00',
 '3342': '43-6012.00',
 '3352': '13-2081.00',
 '3359': '45-2011.00',
 '3412': '21-1093.00',
 '3413': '21-2099.00',
 '3421': '27-2021.00',
 '3431': '27-4021.00',
 '3511': '15-1299.00',
 '3512': '15-1232.00',
 '3513': '15-1231.00',
 '3522': '17-3023.00',
 '4120': '43-6014.00',
 '4131': '43-9022.00',
 '4132': '43-9021.00',
 '4226': '43-4171.00',
 '4227': '43-4111.00',
 '4313': '43-3051.00',
 '4322': '43-5061.00',
 '4323': '43-5032.00',
 '4413': '43-9081.00',
 '4416': '43-4161.00',
 '5132': '35-3011.00',
 '5151': '37-1011.00',
 '5153': '37-2011.00',
 '5161': '27-2099.00',
 '5165': '25-3021.00',
 '5211': '41-9091.00',
 '5221': '11-1021.00',
 '5222': '41-1011.00',
 '5241': '41-9012.00',
 '5242': '41-9011.00',
 '5243': '41-9091.00',
 '5244': '41-9041.00',
 '5312': '25-9042.00',
 '6310': '45-2092.00',
 '6320': '45-2093.00',
 '7111': '11-9021.00',
 '7115': '47-2031.00',
 '7121': '47-2181.00',
 '7125': '47-2121.00',
 '7133': '37-2019.00',
 '7215': '49-9096.00',
 '7313': '51-9071.00',
 '7318': '51-6041.00',
 '7319': '27-1012.00',
 '7322': '51-5112.00',
 '7323': '51-5113.00',
 '7422 ': '49-2097.00',
 '7512': '51-3011.00',
 '7523': '51-7042.00',
 '7531': '51-6052.00',
 '7534': '51-6093.00',
 '7536': '51-6041.00',
 '7541': '49-9092.00',
 '7542': '47-5032.00',
 '7543': '51-9061.00',
 '8132': '51-9151.00',
 '8151': '51-6064.00',
 '8152': '51-6063.00',
 '8153': '51-6031.00',
 '8154': '51-6061.00',
 '8155': '51-6099.00',
 '8156': '51-6042.00',
 '8157': '51-6011.00',
 '8159': '51-6099.00',
 '8172': '51-7041.00',
 '8182': '51-8021.00',
 '8183': '51-9111.00',
 '9111': '37-2012.00',
 '9121': '51-6021.00',
 '9122': '53-7061.00',
 '9123': '37-2011.00',
 '9321': '53-7064.00',
 '9334': '53-7065.00',
 '9510': '39-9099.00',
 '9520': '41-9091.00',
 '9612': '53-7081.00',
 '9613': '37-3019.00',
 '9624': '53-7062.00',
 '2113': '19-2031.00',
 '1112': '11-1021.00',
 '1113': '11-1011.00',
 '1114': '11-1021.00',
 '1120': '11-1021.00',
 '1212': '11-3121.00',
 '1219': '13-1082.00',
 '1221': '11-2022.00',
 '1222': '11-2032.00',
 '1223': '11-9041.00',
 '1343': '11-1021.00',
 '1345': '11-9032.00',
 '1346': '11-1021.00',
 '1431': '13-1082.00',
 '2111': '19-2012.00',
 '2114': '19-2042.00',
 '2120': '15-2031.00',
 '2131': '19-1042.00',
 '2132': '19-1013.00',
 '2133': '19-2041.00',
 '2144': '17-2141.00',
 '2146': '17-2171.00',
 '2149': '17-2199.00',
 '2152': '17-2072.00',
 '2163': '27-1021.00',
 '2165': '17-1022.00',
 '2166': '27-1024.00',
 '2211': '29-1229.00',
 '2212': '29-1229.00',
 '2221': '29-1141.00',
 '2261': '29-1021.00',
 '2263': '19-5011.00',
 '2264': '29-1123.00',
 '2266': '29-1127.00',
 '2269': '29-1122.00',
 '2310': '25-1071.00',
 '2320': '25-1194.00',
 '2341': '25-2021.00',
 '2342': '25-2011.00',
 '2352': '25-2056.00',
 '2353': '25-3021.00',
 '2355': '25-3021.00',
 '2359': '21-1012.00',
 '2411': '13-2011.00',
 '2412': '13-2051.00',
 '2413': '13-2051.00',
 '2421': '13-1111.00',
 '2423': '13-1071.00',
 '2431': '13-1161.00',
 '2433': '41-4011.00',
 '2434': '41-4011.00',
 '2511': '15-1211.00',
 '2512': '15-1252.00',
 '2529': '13-1082.00',
 '2612': '23-1023.00',
 '2621': '25-4012.00',
 '2622': '25-4022.00',
 '2632': '19-3091.00',
 '2633': '19-3099.00',
 '2634': '19-3034.00',
 '2635': '21-1021.00',
 '2636': '21-2011.00',
 '2641': '27-3041.00',
 '2642': '27-3041.00',
 '2643': '27-3091.00',
 '2651': '27-1013.00',
 '2652': '27-2042.00',
 '2653': '27-2031.00',
 '2654': '27-2012.00',
 '2656': '27-3011.00',
 '3111': '19-4099.00',
 '3112': '47-4011.00',
 '3113': '17-3023.00',
 '3115': '17-3029.00',
 '3117': '17-3029.00',
 '3118': '17-3011.00',
 '3119': '19-4099.00',
 '3131': '51-1011.00',
 '3132': '51-1011.00',
 '3134': '51-8093.00',
 '3141': '19-4021.00',
 '3151': '53-1043.00',
 '3152': '53-1043.00',
 '3153': '53-1043.00',
 '3154': '53-1043.00',
 '3211': '29-2034.00',
 '3212': '29-2011.00',
 '3214': '51-9081.00',
 '3240': '29-2056.00',
 '3251': '31-9091.00',
 '3255': '31-9011.00',
 '3256': '31-9092.00',
 '3257': '53-1043.00',
 '3259': '29-1126.00',
 '3311': '41-3031.00',
 '3312': '13-2072.00',
 '3314': '19-4061.00',
 '3315': '13-1031.00',
 '3321': '41-3021.00',
 '3322': '41-3091.00',
 '3323': '13-1023.00',
 '3324': '41-3031.00',
 '3331': '43-5071.00',
 '3333': '13-1071.00',
 '3334': '41-1012.00',
 '3339': '13-1199.00',
 '3343': '43-6011.00',
 '3344': '43-6013.00',
 '3351': '33-3051.00',
 '3353': '13-1041.00',
 '3354': '13-1041.00',
 '3355': '33-3021.00',
 '3411': '23-2011.00',
 '3422': '27-2022.00',
 '3423': '39-9031.00',
 '3432': '27-1026.00',
 '3433': '25-4031.00',
 '3434': '35-1012.00',
 '3435': '27-3099.00',
 '3514': '15-1244.00',
 '3521': '27-4011.00',
 '4110': '43-9061.00',
 '4211': '43-3071.00',
 '4212': '39-3011.00',
 '4213': '41-9099.00',
 '4214': '43-3011.00',
 '4221': '41-1012.00',
 '4222': '43-4051.00',
 '4223': '43-2011.00',
 '4224': '43-4081.00',
 '4225': '43-4171.00',
 '4229': '43-4199.00',
 '4311': '43-3031.00',
 '4312': '43-9041.00',
 '4321': '53-7065.00',
 '4411': '43-4121.00',
 '4412': '43-5052.00',
 '4414': '31-1122.00',
 '4415': '43-4071.00',
 '4419': '43-9199.00',
 '5111': '53-1043.00',
 '5112': '53-1043.00',
 '5113': '39-1022.00',
 '5120': '35-2014.00',
 '5131': '35-3031.00',
 '5141': '39-5012.00',
 '5142': '39-5012.00',
 '5152': '37-1011.00',
 '5162': '31-1122.00',
 '5163': '39-4021.00',
 '5164': '39-1022.00',
 '5169': '35-9031.00',
 '5169 ': '39-9032.00',
 '5212': '35-3041.00',
 '5223': '41-2031.00',
 '5230': '41-2011.00',
 '5245': '53-1043.00',
 '5246': '35-3023.00',
 '5249': '41-2021.00',
 '5311': '39-9011.00',
 '5321': '31-1131.00',
 '5322': '31-1122.00',
 '5329': '31-9091.00',
 '5411': '33-2011.00',
 '5412': '33-3051.00',
 '5413': '33-3012.00',
 '5414': '33-9032.00',
 '5419': '33-9099.00',
 '6111': '45-2091.00',
 '6112': '45-2091.00',
 '6113': '37-1012.00',
 '6114': '45-2091.00',
 '6121': '45-1011.00',
 '6122': '45-1011.00',
 '6123': '45-1011.00',
 '6129': '45-1011.00',
 '6130': '45-2091.00',
 '6210': '45-4022.00',
 '6221': '45-1011.00',
 '6222': '45-1011.00',
 '6223': '45-1011.00',
 '6224': '45-1011.00',
 '6330': '45-2092.00',
 '6340': '45-3031.00',
 '7112': '47-2021.00',
 '7113': '47-2022.00',
 '7114': '47-2051.00',
 '7119': '47-4041.00',
 '7122': '47-2044.00',
 '7123': '47-2081.00',
 '7124': '47-2131.00',
 '7126': '47-2152.00',
 '7127': '49-1011.00',
 '7131': '47-2141.00',
 '7132': '51-9124.00',
 '7211': '51-4072.00',
 '7212': '51-4121.00',
 '7213': '47-2211.00',
 '7214': '51-2041.00',
 '7221': '51-4199.00',
 '7222': '51-4111.00',
 '7223': '51-4041.00',
 '7224': '51-9022.00',
 '7231': '49-3023.00',
 '7232': '49-1011.00',
 '7233': '49-1011.00',
 '7234': '49-1011.00',
 '7311': '49-1011.00',
 '7312': '49-1011.00',
 '7314': '51-9195.00',
 '7315': '51-9195.00',
 '7316': '51-9123.00',
 '7317': '51-7099.00',
 '7321': '51-5111.00',
 '7411': '47-2111.00',
 '7412': '49-1011.00',
 '7413': '49-1011.00',
 '7421': '49-1011.00',
 '7422': '49-1011.00',
 '7511': '51-3022.00',
 '7513': '51-3092.00',
 '7514': '51-3099.00',
 '7515': '45-2041.00',
 '7516': '51-9041.00',
 '7521': '51-9051.00',
 '7522': '51-7011.00',
 '7532': '51-6062.00',
 '7533': '51-6041.00',
 '7535': '45-2041.00',
 '7544': '37-1012.00',
 '7549': '27-1023.00',
 '8111': '47-5022.00',
 '8112': '51-9021.00',
 '8113': '47-5071.00',
 '8114': '51-9023.00',
 '8121': '51-4021.00',
 '8122': '51-9124.00',
 '8131': '51-9011.00',
 '8141': '51-9041.00',
 '8142': '51-4031.00',
 '8143': '51-9196.00',
 '8160': '51-3092.00',
 '8171': '51-9196.00',
 '8181': '51-9023.00',
 '8189': '53-7011.00',
 '8211': '51-2031.00',
 '8212': '51-2022.00',
 '8219': '51-2092.00',
 '8311': '53-1043.00',
 '8312': '53-1043.00',
 '8321': '53-1043.00',
 '8322': '53-3033.00',
 '8331': '53-3051.00',
 '8332': '53-3032.00',
 '8341': '45-2091.00',
 '8342': '47-2073.00',
 '8343': '39-3091.00',
 '8344': '53-7051.00',
 '8350': '53-5011.00',
 '9112': '37-2011.00',
 '9129': '47-4071.00',
 '9211': '45-2092.00',
 '9212': '45-2093.00',
 '9213': '45-2092.00',
 '9214': '37-3011.00',
 '9215': '45-4011.00',
 '9216': '45-2093.00',
 '9311': '47-5081.00',
 '9312': '47-4051.00',
 '9313': '47-2061.00',
 '9329': '53-7062.00',
 '9331': '43-5021.00',
 '9332': '53-6099.00',
 '9333': '53-7062.00',
 '9411': '35-2011.00',
 '9412': '35-2021.00',
 '9611': '53-1043.00',
 '9621': '43-5021.00',
 '9622': '49-9071.00',
 '9623': '43-5041.00',
 '9629': '39-3091.00',
 '0110': '55-1016.00',
 '0210': '55-2013.00',
 '0310': '55-3016.00'}

In [46]:
# Write our CSV
with open(crosswalk_dir + "isco2008_to_onet2019.csv", mode="w", newline="") as file:
    writer = csv.writer(file)

    # CSV header
    writer.writerow(["ISCO-08 Code", 
                     "ISCO-08 Title EN", 
                     "O*NET-SOC 2019 Code", 
                     "O*NET-SOC 2019 Title"])
    
    # Write each key-value pair as a row
    for isco, onet2019 in isco_to_onet2019.items():
        isco_mask = df_isco_soc2010["ISCO-08 Code"] == isco
        isco_title = df_isco_soc2010[isco_mask]["ISCO-08 Title EN"].unique()[0]

        onet_mask = df_onet2019_soc2018["O*NET-SOC 2019 Code"] == onet2019
        onet_title = df_onet2019_soc2018[onet_mask]["O*NET-SOC 2019 Title"].unique()[0]
        writer.writerow([isco, isco_title, onet2019, onet_title])